from django.urls import path
from .views import *


urlpatterns = [
    path('create-products/', ProductListViews.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetailViews.as_view(), name='product_detail'),
    path('create-physical-products/', PhysicalProductListViews.as_view(), name='physical_product_list'),
    path('physical-products/<int:pk>/', PhysicalProductDetailViews.as_view(), name='physical_product_detail'),
    path('create-digital-products/', DigitalProductListViews.as_view(), name='digital_product_list'),
    path('digital-products/<int:pk>/', DigitalProductDetailViews.as_view(), name='digital_product_detail'),
    path('create-products/review/', ProductReviewListView.as_view(), name='review_product_list'),
    path('products/review/<int:pk>/', ProductReviewDetailView.as_view(), name='review_product_detail'),
    path('create-user/', UserListView.as_view(), name='user_list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('create-order-list/', OrderListView.as_view(), name='order_list'),
    path('order-details/<int:pk>/', OrderListDetailView.as_view(), name='orderlist_detail'),
    path('create-order-tracking/', OrderTrackingListView.as_view(), name='order_tracking_list'),
    path('order-tracking/<int:pk>/', OrderTrackingDetailView.as_view(), name='order_tracking_detail'),
    path('create-order-details/', OrderDetailsListView.as_view(), name='order_detail_list'),
    path('order-details/<int:pk>/', OrderDetailsView.as_view(), name='order_detail'),
    path('create-sales/', SalesListView.as_view(), name='sales_list'),
    path('sales/<int:pk>/', SalesDetailView.as_view(), name='sales_detail'),
    path('create-transactions/', TransactionListView.as_view(), name='transactions_list'),
    path('transactions/<int:pk>/', TransactionDetailView.as_view(), name='transactions_detail'),
    path('create-coupons/', ListCoupnsView.as_view(), name='coupons_list'),
    path('coupons/<int:pk>/', ListCoupnsDetailView.as_view(), name='coupons_detail'),
    path('create-coupns/', CreateCouponsListView.as_view(), name='create_coupons_list'),
    path('create-coupons-details/<int:pk>/', CreateCouponsDetailView.as_view(), name='create_coupons_detail'),
    path('create-product-permissions/', ProductRelatedPermissionListView.as_view(), name='product_permissions_list'),
    path('product-permissions/<int:pk>/', ProductRelatedPermissionDetailView.as_view(), name='product_permissions_detail'),
    path('create-category-permissions/', CategoryRelatedPermissionListView.as_view(), name='category_permissions_list'),
    path('category-permissions/<int:pk>/', CategoryRelatedPermissionDetailView.as_view(), name='category_permissions_detail'),
    path('create-taxes/', TaxesListView.as_view(), name='taxes_list'),
    path('taxes-detail/<int:pk>/', TaxesDetailView.as_view(), name='taxes_detail'),
    path('create-invoice/', InvoiceListView.as_view(), name='invoice_list'),
    path('invoice-detail/<int:pk>/', InvoiceDetailView.as_view(), name='invoice_detail'),
]
