# Generated by Django 4.2.1 on 2023-05-12 07:49

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRelatedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_category', models.BooleanField(default=False)),
                ('update_category', models.BooleanField(default=False)),
                ('delete_category', models.BooleanField(default=False)),
                ('apply_discount', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreateCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('freeShipping', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('discount_type', models.CharField(choices=[('PERCENT', 'PERCENT'), ('FIXED', 'FIXED')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
                ('sub_category', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, default=api.models.increment_invoice_number, max_length=500, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('shipping_rate', models.FloatField(max_length=10)),
                ('amount_exc_tax', models.FloatField(max_length=225)),
                ('tax', models.FloatField(max_length=10)),
                ('total_amount', models.FloatField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED')], default=2, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('code', models.CharField(max_length=10, null=True)),
                ('date', models.DateField()),
                ('payment', models.CharField(choices=[('PAYMENT1', 'PAYMENT1'), ('PAYMENT2', 'PAYMENT2'), ('PAYMENT3', 'PAYMENT3'), ('PAYMENT4', 'PAYMENT4')], default='1', max_length=20)),
                ('delivery_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REACHED', 'REACHED')], default='1', max_length=20)),
                ('amount', models.FloatField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
                ('sub_category', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductRelatedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_product', models.BooleanField(default=False)),
                ('update_product', models.BooleanField(default=False)),
                ('delete_product', models.BooleanField(default=False)),
                ('apply_discount', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_detail', models.CharField(max_length=225, null=True)),
                ('tax_rate', models.FloatField(max_length=10, null=True)),
                ('total_tax_amount', models.FloatField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225, null=True)),
                ('lastname', models.CharField(max_length=225, null=True)),
                ('email', models.EmailField(max_length=225, null=True)),
                ('password', models.CharField(max_length=225, null=True)),
                ('confirm_password', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=225, null=True)),
                ('store_name', models.CharField(max_length=225, null=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('revenue', models.FloatField(max_length=10, null=True)),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('PAYMENT1', 'PAYMENT1'), ('PAYMENT2', 'PAYMENT2'), ('PAYMENT3', 'PAYMENT3'), ('PAYMENT4', 'PAYMENT4')], default=1, max_length=225)),
                ('delivery_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REACHED', 'REACHED')], default=1, max_length=225)),
                ('amount', models.FloatField(max_length=25)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderlist')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='media/sales/')),
                ('payment_method', models.CharField(choices=[('PAYMENT1', 'PAYMENT1'), ('PAYMENT2', 'PAYMENT2'), ('PAYMENT3', 'PAYMENT3'), ('PAYMENT4', 'PAYMENT4')], default=1, max_length=225)),
                ('payment_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], default=2, max_length=225)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(max_length=25)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderlist')),
            ],
        ),
    ]
