# Generated by Django 4.2.1 on 2023-05-09 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('freeShipping', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('discount_type', models.CharField(choices=[('PERCENT', 'PERCENT'), ('FIXED', 'FIXED')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('code', models.CharField(max_length=10, null=True)),
                ('date', models.DateField()),
                ('payment', models.CharField(choices=[('PAYMENT1', 'PAYMENT1'), ('PAYMENT2', 'PAYMENT2'), ('PAYMENT3', 'PAYMENT3'), ('PAYMENT4', 'PAYMENT4')], default='1', max_length=20)),
                ('delivery_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REACHED', 'REACHED')], default='1', max_length=20)),
                ('amount', models.FloatField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('PAYMENT1', 'PAYMENT1'), ('PAYMENT2', 'PAYMENT2'), ('PAYMENT3', 'PAYMENT3'), ('PAYMENT4', 'PAYMENT4')], default=1, max_length=225)),
                ('delivery_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REACHED', 'REACHED')], default=1, max_length=225)),
                ('amount', models.FloatField(max_length=25)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderlist')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='media/sales/')),
                ('payment_method', models.CharField(choices=[('PAYMENT1', 'PAYMENT1'), ('PAYMENT2', 'PAYMENT2'), ('PAYMENT3', 'PAYMENT3'), ('PAYMENT4', 'PAYMENT4')], default=1, max_length=225)),
                ('payment_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], default=2, max_length=225)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(max_length=25)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderlist')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
                ('sub_category', models.CharField(max_length=255, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderlist')),
            ],
        ),
        migrations.CreateModel(
            name='ListCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED')], default=2, max_length=20)),
                ('coupon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.createcoupons')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
                ('sub_category', models.CharField(max_length=255, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
