# Generated by Django 4.2.1 on 2023-05-12 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='physicalproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderlist'),
        ),
        migrations.AddField(
            model_name='listcoupons',
            name='coupon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.createcoupons'),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
