# Generated by Django 4.2.1 on 2023-05-11 06:36

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRelatedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_category', models.BooleanField(default=False)),
                ('update_category', models.BooleanField(default=False)),
                ('delete_category', models.BooleanField(default=False)),
                ('apply_discount', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, default=api.models.increment_invoice_number, max_length=500, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('shipping_rate', models.FloatField(max_length=10)),
                ('amount_exc_tax', models.FloatField(max_length=225)),
                ('tax', models.FloatField(max_length=10)),
                ('total_amount', models.FloatField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRelatedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_product', models.BooleanField(default=False)),
                ('update_product', models.BooleanField(default=False)),
                ('delete_product', models.BooleanField(default=False)),
                ('apply_discount', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_detail', models.CharField(max_length=225, null=True)),
                ('tax_rate', models.FloatField(max_length=10, null=True)),
                ('total_tax_amount', models.FloatField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225, null=True)),
                ('lastname', models.CharField(max_length=225, null=True)),
                ('email', models.EmailField(max_length=225, null=True)),
                ('password', models.CharField(max_length=225, null=True)),
                ('confirm_password', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_id',
        ),
        migrations.CreateModel(
            name='VendorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=225, null=True)),
                ('store_name', models.CharField(max_length=225, null=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('revenue', models.FloatField(max_length=10, null=True)),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
